name: spacechooter
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flame: ^1.26.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/bullet.png
    - assets/images/enemy.png
    - assets/images/explosion.png
    - assets/images/player.png    
    - assets/images/stars.png 
